FROM balenalib/%%BALENA_MACHINE_NAME%%-fedora:38

RUN dnf install -y python3 python3-pip

RUN python3 -m pip install pipx

RUN pipx install mitmproxy

RUN pipx ensurepath

ENV PATH="${PATH}:/root/.local/bin/"

CMD [ \
    "mitmweb", \
    "-m", "regular", \
    "--listen-host", "0.0.0.0", \
    "--no-web-open-browser", \
    "--web-host", "0.0.0.0" \
]
